import { Perks, PerksInitialize } from "./Perks";

export type MatchPlayerInfo = {
    assists: number
    baronKills: number
    bountyLevel: number
    champExperience: number
    champLevel: number
    championId: number
    championName: string
    championTransform: number
    consumablesPurchased: number
    damageDealtToBuildings: number
    damageDealtToObjectives: number
    damageDealtToTurrets: number
    damageSelfMitigated: number
    deaths: number
    detectorWardsPlaced: number
    doubleKills: number
    dragonKills: number
    firstBloodAssist: Boolean
    firstBloodKill: Boolean
    firstTowerAssist: Boolean
    firstTowerKill: Boolean
    gameEndedInEarlySurrender: Boolean
    gameEndedInSurrender: Boolean
    goldEarned: number
    goldSpent: number
    individualPosition: string
    inhibitorKills: number
    inhibitorTakedowns: number
    inhibitorsLost: number
    item0: number
    item1: number
    item2: number
    item3: number
    item4: number
    item5: number
    item6: number
    itemsPurchased: number
    killingSprees: number
    kills: number
    lane: string
    largestCriticalStrike: number
    largestKillingSpree: number
    largestMultiKill: number
    longestTimeSpentLiving: number
    magicDamageDealt: number
    magicDamageDealtToChampions: number
    magicDamageTaken: number
    neutralMinionsKilled: number
    nexusKills: number
    nexusLost: number
    nexusTakedowns: number
    objectivesStolen: number
    objectivesStolenAssists: number
    participantId: number
    pentaKills: number
    perks: Perks
    physicalDamageDealt: number
    physicalDamageDealtToChampions: number
    physicalDamageTaken: number
    profileIcon: number
    puuid: string
    quadraKills: number
    riotIdName: string
    riotIdTagline: string
    role: string
    sightWardsBoughtInGame: number
    spell1Casts: number
    spell2Casts: number
    spell3Casts: number
    spell4Casts: number
    summoner1Casts: number
    summoner1Id: number
    summoner2Casts: number
    summoner2Id: number
    summonerId: string
    summonerLevel: number
    summonerName: string
    teamEarlySurrendered: Boolean
    teamId: number
    teamPosition: string
    timeCCingOthers: number
    timePlayed: number
    totalDamageDealt: number
    totalDamageDealtToChampions: number
    totalDamageShieldedOnTeammates: number
    totalDamageTaken: number
    totalHeal: number
    totalHealsOnTeammates: number
    totalMinionsKilled: number
    totalTimeCCDealt: number
    totalTimeSpentDead: number
    totalUnitsHealed: number
    tripleKills: number
    trueDamageDealt: number
    trueDamageDealtToChampions: number
    trueDamageTaken: number
    turretKills: number
    turretTakedowns: number
    turretsLost: number
    unrealKills: number
    visionScore: number
    visionWardsBoughtInGame: number
    wardsKilled: number
    wardsPlaced: number
    win: Boolean
}

export const MatchPlayerInfoInitialize:MatchPlayerInfo =  {
    assists: 11,
    baronKills: 0,
    bountyLevel: 0,
    champExperience: 9250,
    champLevel: 12,
    championId: 22,
    championName: "Ashe",
    championTransform: 0,
    consumablesPurchased: 1,
    damageDealtToBuildings: 0,
    damageDealtToObjectives: 0,
    damageDealtToTurrets: 0,
    damageSelfMitigated: 4609,
    deaths: 7,
    detectorWardsPlaced: 0,
    doubleKills: 0,
    dragonKills: 0,
    firstBloodAssist: true,
    firstBloodKill: false,
    firstTowerAssist: false,
    firstTowerKill: false,
    gameEndedInEarlySurrender: false,
    gameEndedInSurrender: true,
    goldEarned: 7405,
    goldSpent: 7200,
    individualPosition: "Invalid",
    inhibitorKills: 0,
    inhibitorTakedowns: 0,
    inhibitorsLost: 0,
    item0: 3070,
    item1: 4005,
    item2: 6695,
    item3: 3158,
    item4: 1036,
    item5: 1036,
    item6: 0,
    itemsPurchased: 13,
    killingSprees: 0,
    kills: 2,
    lane: "NONE",
    largestCriticalStrike: 116,
    largestKillingSpree: 0,
    largestMultiKill: 1,
    longestTimeSpentLiving: 140,
    magicDamageDealt: 2727,
    magicDamageDealtToChampions: 2099,
    magicDamageTaken: 5808,
    neutralMinionsKilled: 0,
    nexusKills: 0,
    nexusLost: 0,
    nexusTakedowns: 0,
    objectivesStolen: 0,
    objectivesStolenAssists: 0,
    participantId: 1,
    pentaKills: 0,
    perks: PerksInitialize,
    physicalDamageDealt: 18327,
    physicalDamageDealtToChampions: 5492,
    physicalDamageTaken: 4529,
    profileIcon: 4781,
    puuid: "",
    quadraKills: 0,
    riotIdName: "",
    riotIdTagline: "",
    role: "SUPPORT",
    sightWardsBoughtInGame: 0,
    spell1Casts: 7,
    spell2Casts: 67,
    spell3Casts: 9,
    spell4Casts: 6,
    summoner1Casts: 2,
    summoner1Id: 4,
    summoner2Casts: 3,
    summoner2Id: 3,
    summonerId: "",
    summonerLevel: 234,
    summonerName: "Woohk",
    teamEarlySurrendered: false,
    teamId: 100,
    teamPosition: "",
    timeCCingOthers: 39,
    timePlayed: 728,
    totalDamageDealt: 23424,
    totalDamageDealtToChampions: 7591,
    totalDamageShieldedOnTeammates: 0,
    totalDamageTaken: 10577,
    totalHeal: 456,
    totalHealsOnTeammates: 0,
    totalMinionsKilled: 17,
    totalTimeCCDealt: 422,
    totalTimeSpentDead: 118,
    totalUnitsHealed: 1,
    tripleKills: 0,
    trueDamageDealt: 2370,
    trueDamageDealtToChampions: 0,
    trueDamageTaken: 240,
    turretKills: 0,
    turretTakedowns: 0,
    turretsLost: 2,
    unrealKills: 0,
    visionScore: 4,
    visionWardsBoughtInGame: 0,
    wardsKilled: 0,
    wardsPlaced: 0,
    win: false,
}